name: Run examples on push

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  sigma-dao-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: "16"
          cache: "yarn"
      - name: Install dependencies
        run: yarn install
      - name: Build packages
        run: yarn build

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pipenv"
      - name: Install poetry
        run: pip install -U poetry
      - name: Install pipenv
        run: python -m pip install pipenv
      - run: pipenv sync

      - name: Install Algorand
        run: |
          sudo apt-get update && sudo apt-get install -y gnupg2 curl software-properties-common
          curl -O https://releases.algorand.com/key.pub && sudo apt-key add key.pub
          sudo add-apt-repository "deb [arch=amd64] https://releases.algorand.com/deb/ stable main"
          sudo apt-get update && sudo apt-get install -y algorand
      - name: Setup Network
        run: cd infrastructure && make setup-private-net

      - name: Example DAO
        working-directory: ./examples/dao
        run: |
          pipenv run yarn algob deploy
          pipenv run yarn algob run scripts/run/add_proposal.js
          pipenv run yarn algob run scripts/run/deposit_vote_token.js

